In [15]:
import numpy as np

data = np.random.randn(10, 3)
print("Data is, \n", data, end='\n\n')

N = data.shape[0]
print("N is", N, end='\n\n')
    
    # using random.choice for random index to pull out and take the whole row and column of that index from data
    # to centers, same type of 2d array
idx = np.random.choice(N, 4, replace=False)
print("random idx: ", idx, end='\n\n')

centers = data[idx, :]
print("centers are :\n", centers, end='\n\n')
    
    # iteration for niter times
for i in range(3):
    
    print("i th round: ", i, end='\n')
    print("centers.shape: ", centers.shape, end='\n\n')
    print("centers: ", centers, end='\n\n')
    print("centers with np.newaxis: ", centers[:, np.newaxis, :], end='\n\n')
    sq_dists = np.sum((centers[: ,np.newaxis, :] - data)**2, axis=2)
    print("np.sum :", sq_dists)
    closest  = np.argmin(sq_dists, axis=0) 
    for j in range(2):
        centers[j,:] = data[closest==j,:].mean(axis=0)


Data is, 
 [[-1.75680864 -0.82812416 -0.46973191]
 [-0.63719054  0.53403281 -0.59056629]
 [ 0.59931033 -0.03878025 -0.9125311 ]
 [-0.29673096 -0.43139636 -0.53344119]
 [ 0.40029357  1.43945523  0.98273365]
 [ 0.42877467  0.28064705 -0.90128346]
 [-0.72736967 -0.39886281  2.12366961]
 [ 0.27692053 -0.40612745 -1.40943249]
 [ 0.24956682  0.49761694  0.23396864]
 [ 0.66118712  0.99551844 -0.18293457]]

N is 10

random idx:  [2 3 9 8]

centers are :
 [[ 0.59931033 -0.03878025 -0.9125311 ]
 [-0.29673096 -0.43139636 -0.53344119]
 [ 0.66118712  0.99551844 -0.18293457]
 [ 0.24956682  0.49761694  0.23396864]]

i th round:  0
centers.shape:  (4, 3)

centers:  [[ 0.59931033 -0.03878025 -0.9125311 ]
 [-0.29673096 -0.43139636 -0.53344119]
 [ 0.66118712  0.99551844 -0.18293457]
 [ 0.24956682  0.49761694  0.23396864]]

centers with np.newaxis:  [[[ 0.59931033 -0.03878025 -0.9125311 ]]

 [[-0.29673096 -0.43139636 -0.53344119]]

 [[ 0.66118712  0.99551844 -0.18293457]]

 [[ 0.24956682  0.49761694  0.23