In [26]:
import numpy as np

W = np.array([[4,20, 6, 12],[10,3, 4, 5],[1,5, 21, 40], [100,30, 2, 3]])    
print(W, end ='\n\n')
k = 1
Wk = W[0:5,:]
print(Wk)



[[  4  20   6  12]
 [ 10   3   4   5]
 [  1   5  21  40]
 [100  30   2   3]]

[[  4  20   6  12]
 [ 10   3   4   5]
 [  1   5  21  40]
 [100  30   2   3]]


In [27]:
image = np.zeros( (8,64,64) )

In [29]:
print(image.shape)

(8, 64, 64)


In [31]:
i_vals = np.concatenate((np.asarray([1]),np.arange(10,110,step=10), np.arange(120,220,step=20)))


In [32]:
print(i_vals)

[  1  10  20  30  40  50  60  70  80  90 100 120 140 160 180 200]


In [ ]:
i_s = [1, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 120, 140, 160, 180, 200]

for k, i in enumerate(i_s):
    pca = PCA(n_components=i)
    pca.fit(X)
    
    restored = pca.inverse_transform(pca.transform(X_t))
    
    plt.title("ith: ", i)
    figure()
    imshow(restored.reshape((h,w)), cmap=cm.Greys_r)